cd gto_amino_acid_to_group
sh runExample.sh
cd ..
cd gto_amino_acid_to_pseudo_dna
sh runExample.sh
cd ..
cd gto_brute_force_string
sh runExample.sh
cd ..
cd gto_char_to_line
sh runExample.sh
cd ..
cd gto_comparative_map
sh runExample.sh
cd ..
cd gto_fasta_extract
sh runExample.sh
cd ..
cd gto_fasta_extract_by_read
sh runExample.sh
cd ..
cd gto_fasta_extract_pattern_coords
sh runExample.sh
cd ..
cd gto_fasta_extract_read_by_pattern
sh runExample.sh
cd ..
cd gto_fasta_find_n_pos
sh runExample.sh
cd ..
cd gto_fasta_from_seq
sh runExample.sh
cd ..
cd gto_fasta_info
sh runExample.sh
cd ..
cd gto_fasta_mutate
sh runExample.sh
cd ..
cd gto_fasta_rand_extra_chars
sh runExample.sh
cd ..
cd gto_fasta_rename_human_headers
sh runExample.sh
cd ..
cd gto_fasta_split_reads
sh runExample.sh
cd ..
cd gto_fasta_to_seq
sh runExample.sh
cd ..
cd gto_fastq_cut
sh runExample.sh
cd ..
cd gto_fastq_exclude_n
sh runExample.sh
cd ..
cd gto_fastq_extract_quality_scores
sh runExample.sh
cd ..
cd gto_fastq_from_seq
sh runExample.sh
cd ..
cd gto_fastq_info
sh runExample.sh
cd ..
cd gto_fastq_maximum_read_size
sh runExample.sh
cd ..
cd gto_fastq_minimum_local_quality_score_forward
sh runExample.sh
cd ..
cd gto_fastq_minimum_local_quality_score_reverse
sh runExample.sh
cd ..
cd gto_fastq_minimum_quality_score
sh runExample.sh
cd ..
cd gto_fastq_minimum_read_size
sh runExample.sh
cd ..
cd gto_fastq_mutate
sh runExample.sh
cd ..
cd gto_fastq_pack
sh runExample.sh
cd ..
cd gto_fastq_quality_score_info
sh runExample.sh
cd ..
cd gto_fastq_quality_score_max
sh runExample.sh
cd ..
cd gto_fastq_quality_score_min
sh runExample.sh
cd ..
cd gto_fastq_rand_extra_chars
sh runExample.sh
cd ..
cd gto_fastq_split
sh runExample.sh
cd ..
cd gto_fastq_to_fasta
sh runExample.sh
cd ..
cd gto_fastq_to_mfasta
sh runExample.sh
cd ..
cd gto_fastq_unpack
sh runExample.sh
cd ..
cd gto_filter
sh runExample.sh
cd ..
cd gto_genomic_count_bases
sh runExample.sh
cd ..
cd gto_genomic_dna_mutate
sh runExample.sh
cd ..
cd gto_genomic_extract
sh runExample.sh
cd ..
cd gto_genomic_gen_random_dna
sh runExample.sh
cd ..
cd gto_genomic_period
sh runExample.sh
cd ..
cd gto_genomic_rand_seq_extra_chars
sh runExample.sh
cd ..
cd gto_info
sh runExample.sh
cd ..
cd gto_lower_bound
sh runExample.sh
cd ..
cd gto_new_line_on_new_x
sh runExample.sh
cd ..
cd gto_permute_by_blocks
sh runExample.sh
cd ..
cd gto_real_to_binary_with_threshold
sh runExample.sh
cd ..
cd gto_reverse
sh runExample.sh
cd ..
cd gto_segment
sh runExample.sh
cd ..
cd gto_sum
sh runExample.sh
cd ..
cd gto_upper_bound
sh runExample.sh
cd ..
cd gto_word_search
sh runExample.sh
cd ..
cd gto_max
sh runExample.sh
cd ..
cd gto_min
sh runExample.sh
cd ..
cd gto_ac
sh runExample.sh
cd ..
cd gto_xs
sh runExample.sh
cd ..